# Generated by Django 5.0.6 on 2024-08-11 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('organizer', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/images')),
                ('attendees', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('attendeesUser', models.ManyToManyField(blank=True, related_name='attended_events', to=settings.AUTH_USER_MODEL)),
                ('eventCreator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventCreator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['title'], name='events_even_title_aedf91_idx'), models.Index(fields=['location'], name='events_even_locatio_0ae1f4_idx'), models.Index(fields=['start_datetime'], name='events_even_start_d_b72861_idx'), models.Index(fields=['end_datetime'], name='events_even_end_dat_53a75f_idx'), models.Index(fields=['created_at'], name='events_even_created_52c227_idx'), models.Index(fields=['updated_at'], name='events_even_updated_1878aa_idx'), models.Index(fields=['eventCreator'], name='events_even_eventCr_bdf27a_idx'), models.Index(fields=['organizer'], name='events_even_organiz_175c79_idx')],
            },
        ),
    ]
