# Generated by Django 5.0.6 on 2024-08-11 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendeesUser',
        ),
    ]
