# Generated by Django 5.0.6 on 2026-05-12 04:16

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_attendeesuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.utils.secure_hash_filename),
        ),
    ]
