# Generated by Django 5.0.6 on 2024-06-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_image',
            field=models.FileField(upload_to='users/id_card_image'),
        ),
    ]
