# Generated by Django 5.0.6 on 2024-06-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_card_image',
            field=models.ImageField(upload_to='users/id_card_image'),
        ),
    ]
