# Generated by Django 5.0.6 on 2024-07-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
