# Generated by Django 5.0.6 on 2024-08-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='userBio',
            field=models.CharField(blank=True, null=True),
        ),
    ]
