# Generated by Django 5.0.6 on 2024-07-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
