# Generated by Django 5.0.6 on 2024-08-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_userbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userBio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
