# Generated by Django 5.0.6 on 2024-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_user_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='users/profile_picture', width_field='image_width'),
        ),
    ]
