# Generated by Django 5.0.6 on 2024-07-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_image_height_userprofile_image_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to='users/cover_photo', width_field='cover_width'),
        ),
    ]
