# Generated by Django 5.0.6 on 2024-08-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
