# Generated by Django 5.0.6 on 2024-08-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_agree_to_terms_alter_user_collage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_privet',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
