# Generated by Django 5.0.6 on 2024-09-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='users_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
