# Generated by Django 5.0.6 on 2026-04-10 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_users_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='accounts.message')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to='accounts.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_read'], name='accounts_me_user_id_4b147c_idx'), models.Index(fields=['user', '-created_at'], name='accounts_me_user_id_7dd9a1_idx')],
            },
        ),
    ]
