# Generated by Django 5.0.6 on 2026-04-27 16:41

from django.db import migrations, models


def populate_normalized_name(apps, schema_editor):
    """Populate normalized_name for existing colleges."""
    College = apps.get_model('accounts', 'College')
    for college in College.objects.all():
        # Normalize: uppercase, trim, collapse spaces
        normalized = ' '.join(college.name.strip().split()).upper()
        college.normalized_name = normalized
        college.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_college_remove_user_collage_name_user_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='college',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='college',
            name='normalized_name',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(populate_normalized_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
