# Generated by Django 5.0.6 on 2026-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_college_city_college_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
