# Generated by Django 5.0.6 on 2026-04-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_college_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='aishe_code',
            field=models.CharField(blank=True, help_text='Official Government AISHE Code', max_length=50, null=True, unique=True),
        ),
    ]
