# Generated by Django 5.0.6 on 2026-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_college_aishe_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, db_index=True, help_text='Indian State or Union Territory', max_length=100, null=True),
        ),
    ]
