# Generated by Django 5.0.6 on 2026-08-16 10:04

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to=accounts.utils.secure_hash_filename),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, height_field='cover_height', null=True, upload_to=accounts.utils.secure_hash_filename, width_field='cover_width'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=accounts.utils.secure_hash_filename, width_field='image_width'),
        ),
    ]
