# Generated by Django 5.0.6 on 2024-07-11 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0002_userposts_post_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userposts',
            options={'verbose_name': 'UserPost', 'verbose_name_plural': 'UserPosts'},
        ),
    ]
