# Generated by Django 5.0.6 on 2024-08-06 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
