# Generated by Django 5.0.6 on 2024-08-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0003_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='caption',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
