# Generated by Django 5.0.6 on 2024-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0004_remove_userposts_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='caption',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='content',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
