# Generated by Django 5.0.6 on 2024-08-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0004_alter_userposts_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='caption',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
