# Generated by Django 5.0.6 on 2024-07-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0005_alter_userposts_caption_alter_userposts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='post_slug',
            field=models.SlugField(unique=True),
        ),
    ]
