# Generated by Django 5.0.6 on 2024-07-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0006_alter_userposts_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userposts',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userposts',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='post_image',
            field=models.ImageField(blank=True, height_field='image,height', null=True, upload_to='users/posts/post_image', width_field='image_width'),
        ),
    ]
