# Generated by Django 5.0.6 on 2026-04-18 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0007_alter_notification_post_alter_notification_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='list_posts.userposts'),
        ),
    ]
