# Generated by Django 5.0.6 on 2024-07-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0007_userposts_image_height_userposts_image_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='caption',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='post_image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='users/posts/post_image', width_field='image_width'),
        ),
    ]
