# Generated by Django 5.0.6 on 2024-07-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0008_alter_userposts_caption_alter_userposts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='content',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
