# Generated by Django 5.0.6 on 2026-08-16 10:04

import django.db.models.deletion
import list_posts.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0008_alter_notification_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedPost',
            fields=[
            ],
            options={
                'verbose_name': 'Flagged Post',
                'verbose_name_plural': 'Flagged Posts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('list_posts.userposts',),
        ),
        migrations.AlterField(
            model_name='userposts',
            name='post_image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=list_posts.utils.secure_hash_filename, width_field='image_width'),
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('nudity', 'Nudity'), ('bullying', 'Bullying'), ('suicide', 'Suicide'), ('violence', 'Violence'), ('hate', 'Hate'), ('spam', 'Spam')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='list_posts.userposts')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Report',
                'verbose_name_plural': 'Post Reports',
                'unique_together': {('post', 'reporter')},
            },
        ),
    ]
