# Generated by Django 5.0.6 on 2026-05-12 04:16

import list_posts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0008_alter_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='post_image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to=list_posts.utils.secure_hash_filename, width_field='image_width'),
        ),
    ]
