# Generated by Django 5.0.6 on 2026-08-16 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0009_alter_userposts_post_image'),
        ('list_posts', '0009_flaggedpost_alter_userposts_post_image_postreport'),
    ]

    operations = [
    ]
