# Generated by Django 5.0.6 on 2024-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0009_alter_userposts_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
