# Generated by Django 5.0.6 on 2024-07-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_posts', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_msg',
            field=models.CharField(blank=True, null=True),
        ),
    ]
