"""
Django settings for amity_social_main project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from decouple import config
from pathlib import Path
import os
from django import conf
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.api



BASE_DIR = Path(__file__).resolve().parent.parent
# config = Config(RepositoryEnv(os.path.join(BASE_DIR, '.env')))



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False', cast=bool)
# for local development 
# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')



# Application definition

INSTALLED_APPS = [
    "daphne",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'accounts',
    'list_posts',
    'events',
    'django_ratelimit',
    'compressor',
    'cloudinary',
    'cloudinary_storage',
]



# settings.py for local development with redis and channels
# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             "hosts": [f"redis://:{config('REDIS_PASSWORD', default='')}@{config('REDIS_HOST', default='127.0.0.1')}:{config('REDIS_PORT', default='6379', cast=int)}/0"],
#         },
#     },
# }



# STATICFILES_STORAGE = 'compressor.storage.CompressorFileStorage'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = not DEBUG  # Set to True if you want to pre-compress files during deployment



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'amity_social_main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.get_user_profile',
            ],
        },
    },
]

# WSGI_APPLICATION = 'amity_social_main.wsgi.application'
ASGI_APPLICATION = 'amity_social_main.asgi.application'


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# for local development with postgresql 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME':config('DB_NAME'),
#         'USER':config('DB_USER'),
#         'PASSWORD':config('DB_PASSWORD'),
#         'HOST':config('DB_HOST'),
#     }
# }
# for local development with postgresql 
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME':config('DB_NAME'),
#         'USER':config('DB_USER'),
#         'PASSWORD':config('DB_PASSWORD'),
#         'HOST':config('DB_HOST'),
#     }
# }



if config('DATABASE_URL', default=None):
    DATABASES = {
        'default': dj_database_url.config(
            default=config('DATABASE_URL')
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME', default='your_db_name'),
            'USER': config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default=''),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
        }
    }
AUTH_USER_MODEL = 'accounts.User'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Set the timezone to India
TIME_ZONE = 'Asia/Kolkata'

# Ensure that Django uses timezone-aware datetimes
USE_TZ = True

USE_I18N = True




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
#for local development
#STATIC_URL = 'static/'
# for local development
# STATIC_ROOT = BASE_DIR /'static'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'amity_social_main/static/'),
# ]
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# for production devlopment 

import os

STATIC_URL = '/static/'   # ✅ MUST have leading /

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),   # ✅ important
]
# media files  for local 
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': config('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': config('CLOUDINARY_API_KEY'),
    'API_SECRET': config('CLOUDINARY_API_SECRET'),
}

STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


COMPRESS_URL = STATIC_URL
COMPRESS_ROOT = STATIC_ROOT

#Email setup
# Email setup
# EMAIL_TIMEOUT = 15  # Increased slightly to give the handshake more time
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = config('EMAIL_HOST')
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_PORT = config('EMAIL_PORT', cast=int) 
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# # Make these dynamic so Railway variables actually work
# EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
# EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)

# # This must match your verified SendGrid identity
# DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='collages.socialmedia@gmail.com')

# Email setup using SendGrid Web API
EMAIL_BACKEND = "sendgrid_backend.SendgridBackend"

# Decouple won't crash if you provide a default fallback or if the var exists
SENDGRID_API_KEY = config("SENDGRID_API_KEY", default="")

# Ensure this matches your verified SendGrid single sender identity
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="collages.socialmedia@gmail.com")

# Optional config
SENDGRID_SANDBOX_MODE_IN_DEBUG = False

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost',
    cast=lambda v: [s.strip() for s in v.split(',')]
)


CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://sweet-recreation-production-d238.up.railway.app',
    'https://amity.loca.lt',
    'https://afraid-ads-swim.loca.lt',
    'https://harvey-rendered-toolkit-ali.trycloudflare.com',
]

# Security settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default='True', cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default='True', cast=bool)
CSRF_COOKIE_HTTPONLY = False
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'

# Content Security Policy (CSP)
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'", "'unsafe-eval'")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", 'data:', 'blob:', 'https://res.cloudinary.com')
CSP_MEDIA_SRC = ("'self'", 'https://res.cloudinary.com')
CSP_FONT_SRC = ("'self'", 'data:')
CSP_CONNECT_SRC = ("'self'", 'wss:', 'ws:')
CSP_OBJECT_SRC = ("'none'",)
CSP_FRAME_ANCESTORS = ("'none'",)
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = ("'self'",)


# caching for local development with redis, using database cache as fallback
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': f"redis://:{config('REDIS_PASSWORD', default='')}@{config('REDIS_HOST', default='127.0.0.1')}:{config('REDIS_PORT', default='6379')}/1",
#         'TIMEOUT': 60,
#         'OPTIONS': {
#             'socket_connect_timeout': 5,
#         }
#     }
# }


#for local env
# REDIS_URL = config('REDIS_PUBLIC_URL', default='redis://127.0.0.1:6379/1')
# for production env
# Check for standard Railway CLI injection (REDIS_URL) first, then fallback to public URL variation
# Check for standard Railway CLI injection (REDIS_URL) first, then fallback to public URL variation
raw_redis_url = config('REDIS_URL', default=config('REDIS_PUBLIC_URL', default=None))

def is_valid_redis_url(url):
    if not url or not isinstance(url, str):
        return False
    if '${{' in url or '}}' in url:
        return False
    return url.startswith('redis://') or url.startswith('rediss://')

REDIS_URL = raw_redis_url if is_valid_redis_url(raw_redis_url) else None

if REDIS_URL:
    CACHES = {
        "default": {
            # Switch to django-redis backend for better production stability on Railway
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                # Wrap the connection string securely for Daphne/Channels
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # Safe Local Fallback if Redis isn't running locally
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "unique-snowflake",
        }
    }
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        },
    }
    print(f"WARNING: Redis not configured (got: {raw_redis_url}). Using local memory.")
# Silence django-ratelimit system checks for non-shared cache backends
SILENCED_SYSTEM_CHECKS = [
    'django_ratelimit.E003',
    'django_ratelimit.W001',
]
# for local 
# Fallback to locmem if redis not available (development)
# try:
#     import redis
#     redis_host = config('REDIS_HOST', default='127.0.0.1')
#     redis_port = config('REDIS_PORT', default='6379', cast=int)
#     redis_password = config('REDIS_PASSWORD', default=None)
#     r = redis.Redis(host=redis_host, port=redis_port, db=1, password=redis_password)
#     r.ping()
# except:
#     CACHES = {
#         'default': {
#             'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#             'LOCATION': 'unique-snowflake',
#         }
#     }


import logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "DEBUG",
    },
}